version: 0.2
          
phases:
  install:
    commands: 
  pre_build:
    commands:      
  build:
    commands:
      - node main.js
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no